"""empty message

Revision ID: ae538bc531d1
Revises: 49ceabf8dd83
Create Date: 2016-03-26 13:30:17.792840

"""

# revision identifiers, used by Alembic.
revision = 'ae538bc531d1'
down_revision = '49ceabf8dd83'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_wishlist',
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.id'], )
    )
    op.drop_table('items')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('wishlist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], [u'item.id'], name=u'items_ibfk_1'),
    sa.ForeignKeyConstraint(['wishlist_id'], [u'wishlist.id'], name=u'items_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('item_wishlist')
    ### end Alembic commands ###
