"""empty message

Revision ID: c6d3a30f87ec
Revises: 10cbfe156c2c
Create Date: 2016-03-28 19:15:00.804698

"""

# revision identifiers, used by Alembic.
revision = 'c6d3a30f87ec'
down_revision = '10cbfe156c2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('name', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'name')
    ### end Alembic commands ###
